[package]
name = "stream-processor"
version = "0.1.0"
authors = ["Sebastian Rollen <seb@overmu.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.13"
rdkafka = { version = "0.26", features = ["ssl-vendored"] }
serde = "1.0.125"
serde_json = "1.0.64"
thiserror = "1.0.24"
tracing = "0.1.25"

[dev-dependencies]
tokio = { version = "1.4.0", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.2.17"
